# Generated by Django 5.2.7 on 2026-01-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
